Repository thoth-station/sesheta, pull requests merged in 2018-07, with the labels that each got.

#1 added the zuul project config
  .zuul.yaml
  sesheta/utils.py
Labels: approved

#3 Automatic update of dependency pytest-timeout from 1.3.0 to 1.3.1
  Pipfile.lock
Labels: bot

#5 Automatic update of dependency pytest from 3.6.3 to 3.6.4
  Pipfile.lock
Labels: bot

#9 Release of version 2.1.0
  sesheta/__init__.py
Labels: bot, size/XS

#11 Automatic update of dependency pytest from 3.6.4 to 3.7.0
  Pipfile.lock
Labels: bot
