Repository thoth-station/sesheta, pull requests merged in 2018-09, with the labels that each got.

#33 Automatic update of dependency pytest-cov from 2.5.1 to 2.6.0
  Pipfile.lock
Labels: bot

#30 Ignore lines that do not stated related issue in releases
  sesheta/webhooks.py
Labels: approved, size/XS

#35 Automatic update of dependency pytest from 3.7.4 to 3.8.0
  Pipfile.lock
Labels: bot

#36 Automatic update of dependency pygithub from 1.40 to 1.43
  Pipfile.lock
Labels: bot

#38 Automatic update of dependency pygithub from 1.43 to 1.43.1
  Pipfile.lock
Labels: bot

#43 Automatic update of dependency pytest from 3.8.0 to 3.8.1
  Pipfile.lock
Labels: bot

#45 fixed a KeyError exception, the ugly way
  sesheta/webhooks.py
Labels: size/XS
