Repository thoth-station/sesheta, pull requests merged in 2018-08, with the labels that each got.

#12 added notification if a PR has a 'needs-rebase' label
  README.md
  fixtures/pull_request_labeled.json
  sesheta/webhook_processors/github_pull_requests.py
  sesheta/webhooks.py
Labels: approved, size/XL

#13 reduced the noise a little
  sesheta/webhook_processors/github_reviews.py
Labels: approved, size/XS

#14 Automatic update of dependency pytest from 3.7.0 to 3.7.1
  Pipfile.lock
Labels: bot

#15 fixed some of the codacy issues
  sesheta/utils.py
  sesheta/webhook_processors/github_reviews.py
  sesheta/webhooks.py
  tests/test_pull_requests.py
  tests/test_reviews.py
  tests/test_utils.py
  wsgi.py
Labels: approved, size/M

#21 Automatic update of dependency pytest from 3.7.1 to 3.7.3
  Pipfile.lock
Labels: bot

#24 Automatic update of dependency pytest-timeout from 1.3.1 to 1.3.2
  Pipfile.lock
Labels: bot

#25 Automatic update of dependency pytest from 3.7.3 to 3.7.4
  Pipfile.lock
Labels: bot
