Repository thoth-station/sesheta, pull requests merged in 2018-10, with the labels that each got.

#48 implemented sentry
  Pipfile
  Pipfile.lock
  sesheta/__init__.py
  wsgi.py
Labels: approved, size/M

#49 Automatic update of dependency pytest from 3.8.1 to 3.8.2
  Pipfile.lock
Labels: bot

#51 Automatic update of dependency thoth-common from 0.3.6 to 0.3.7
  Pipfile.lock
Labels: bot

#52 Automatic update of dependency thoth-common from 0.3.7 to 0.3.8
  Pipfile.lock
Labels: bot

#53 Automatic update of dependency thoth-common from 0.3.8 to 0.3.9
  Pipfile.lock
Labels: bot

#54 Automatic update of dependency thoth-common from 0.3.9 to 0.3.10
  Pipfile.lock
Labels: bot

#55 Automatic update of dependency thoth-common from 0.3.10 to 0.3.11
  Pipfile.lock
Labels: bot

#56 Automatic update of dependency pytest from 3.8.2 to 3.9.1
  Pipfile.lock
Labels: bot

#57 Automatic update of dependency autopep8 from 1.4 to 1.4.1
  Pipfile.lock
Labels: bot

#58 added a few missing repos
  config.yaml
  sesheta/__init__.py
Labels: approved, size/M

#59 Automatic update of dependency requests from 2.19.1 to 2.20.0
  Pipfile.lock
Labels: bot

#60 Automatic update of dependency thoth-common from 0.3.11 to 0.3.12
  Pipfile.lock
Labels: bot

#61 Automatic update of dependency pytest from 3.9.1 to 3.9.2
  Pipfile.lock
Labels: bot

#62 Automatic update of dependency autopep8 from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: bot

#64 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/M

#65 Automatic update of dependency thoth-common from 0.3.12 to 0.3.13
  Pipfile.lock
Labels: bot

#66 Automatic update of dependency thoth-common from 0.3.13 to 0.3.14
  Pipfile.lock
Labels: bot

#67 Automatic update of dependency thoth-common from 0.3.14 to 0.3.15
  Pipfile.lock
Labels: bot

#69 Automatic update of dependency pygithub from 1.43.2 to 1.43.3
  Pipfile.lock
Labels: bot
