Repository thoth-station/sesheta, pull requests merged in 2019-02, with the labels that each got.

#109 Automatic update of dependency pygithub from 1.43.4 to 1.43.5
  Pipfile.lock
Labels: bot

#106 Automatic update of dependency pylint from 2.3.0.dev0 to 2.3.0.dev1
  Pipfile.lock
Labels: bot

#111 Automatic update of dependency pytest from 4.1.1 to 4.2.1
  Pipfile.lock
Labels: bot

#113 minor changes for coala
  .zuul.yaml
  openshift/cronJob-template.yaml
  playbooks/provision.yaml
  scrum_standup.py
  sesheta/utils.py
Labels: approved, size/M

#112 added missing projects
  config.json
  sesheta/__init__.py
Labels: approved, size/S

#108 Automatic update of dependency google-api-python-client from 1.7.7 to 1.7.8
  Pipfile.lock
Labels: bot

#115 Automatic update of dependency thoth-common from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: bot

#116 Automatic update of dependency pytest from 4.2.1 to 4.3.0
  Pipfile.lock
Labels: bot

#117 Automatic update of dependency pylint from 2.3.0.dev1 to 2.3.0.dev2
  Pipfile.lock
Labels: bot

#118 Automatic update of dependency pylint from 2.3.0.dev2 to 2.3.0
  Pipfile.lock
Labels: bot
